### ISSUE TITLE
How to use choose biometric type i.e. fingerprint or facial biometrics on Android

### ISSUE THREAD

**Issue by Kaayo** [FreakyAli/Plugin.Maui.Biometric#4] opened 2024-05-07 15:48 UTC
Hello, I downloaded the test application from repository: https://github.com/jfversluis/MauiBiometricPluginSample and it works great authenticating using your finger. But face authentication isn't working. The phone I use for the tests is a Xiaomi Mi M9T that allows biometrics using the finger and face. How do I choose which biometrics I want to use? Grateful

**Comment by FreakyAli** [comment] 2024-05-07 16:09
So face recognition on Android was unsupported until quite recently, it is now supported on Android 10 plus and I just got the documentation for it a couple days ago, for the time being this is a feature which is in progress, I am planning to add this asap but it might take some time, hope you don't mind. 

More information on this here https://source.android.com/docs/security/features/biometric/face-authentication

**Comment by FreakyAli** [comment] 2024-05-07 17:15
@Kaayo When you try to use Weak Authentication with Android does it allow you to use Face recognition can you please confirm?

**Comment by Kaayo** [comment] 2024-05-07 17:20
> @Kaayo When you try to use Weak Authentication with Android does it allow you to use Face recognition can you please confirm?

As soon as possible I will perform the test and let you know here.

if you need help testing on the Android platform in the future, I'm at your disposal. This plugin is very requested in my projects and I believe it will help the community as a whole. Go on.

**Comment by FreakyAli** [comment] 2024-05-07 17:49
I just verified and it is working with Weak Auth, the only issue is you cannot have a fingerprint enrolled, if you want it to instead choose from face recognition/fingerprint,  you need to use the old deprecated APIs from FingerprintManager... https://issuetracker.google.com/issues/111315641?pli=1

I need suggestions here do you think we should implement those deprecated APIs for this option or wait for Google to add this option to their latest APIs?

Also once you test don't close this bug, `GetAuthenticationStatusAsync` needs to fix a bug related to this and this issue can be a tracker for this or may be i will raise another bug for it idk for now 

![image](https://github.com/FreakyAli/Plugin.Maui.Biometric/assets/31090457/fa026f31-877e-4f34-ba24-2c4c1431507d)

**Comment by Kaayo** [comment] 2024-05-07 18:13
> Preciso de sugestões aqui, você acha que devemos implementar essas APIs preteridas para essa opção ou esperar que o Google adicione essa opção às suas APIs mais recentes?

I think that to meet the demand of all developers, including mine currently.

It is better to make the old APIs available (Facial and Finger) and in parallel work and wait for the new Google APIs.

So we don't force anyone to wait to use the plugin, but it's important to let us know in the repository that in the future in the new versions a new way of implementing the library in projects may be addressed, which may cause breaks in the application code, and developers they should update their codebases.

**Comment by FreakyAli** [comment] 2024-05-08 11:03
> It is better to make the old APIs available (Facial and Finger) and in parallel work and wait for the new Google APIs.

Okay, I will do some RnD and see if we can do this and how exactly would it be done, If possible i will try to add this feature over the weekend

**Comment by FreakyAli** [comment] 2024-05-13 14:33
@Kaayo Since the code that will be used in this will be a bunch of deprecated native android code, I am gonna mark it as such hope that is not a problem for you!

**Comment by FreakyAli** [comment] 2024-05-13 16:16
I think we have a small problem... 

https://stackoverflow.com/a/59685507/7462031

**Comment by FreakyAli** [comment] 2024-05-13 16:24
Even the image from the original Android studio face ID thing makes it clear, but I somehow missed it 

![image](https://github.com/FreakyAli/Plugin.Maui.Biometric/assets/31090457/bc4a8ec5-d61a-4e06-92cb-59ab51a2b622)


https://source.android.com/docs/security/features/biometric/face-authentication

**Comment by Kaayo** [comment] 2024-05-13 19:29
> Uma vez que o código que será usado neste será um monte de código Android nativo preterido, vou marcá-lo como tal espero que não seja um problema para você!

For me, I would have no problem leaving the legacy API code as "deprecated".

**Comment by Kaayo** [comment] 2024-05-13 19:32
> I think we have a small problem...
> 
> Choosing between the two is not possible at all on Android, the old deprecated APIs are fingerprint only!
> 
> When I initially read the documentation, I misunderstood what it said, I thought it meant that the old APIs had a way for the developer to specifying what the user can choose to Authenticate themselves, Whereas what it is, is that when the user authenticates you know how they did it...
> 
> https://stackoverflow.com/a/59685507/7462031

Apparently, we're going to need to wait for Google to make some example of lower-level code available for you to adapt or we're going to maybe need help from someone who understands the lower-level code, or am I mistaken?

**Comment by FreakyAli** [comment] 2024-05-13 19:45
I already understand the native code, the problem is in our previous discussion I had just checked the documentation from a very high level, as I went deep I realised what we need hear is not natively possible at all

**Comment by Kaayo** [comment] 2024-05-14 13:55
> I already understand the native code, the problem is in our previous discussion I had just checked the documentation from a very high level, as I went deep I realised what we need here is not natively possible at all

Understand. I believe that maybe by talking to the Microsoft community they could maybe give us a direction or make some more up-to-date API available for NET CORE/MAUI. Maybe this guy can help us: https://www.youtube.com/@jfversluis, he made a video of his plugin.

**Comment by FreakyAli** [comment] 2024-05-14 13:58
I don't think anyone at Microsoft can help us with this, this has nothing to do with .NET or .NET MAUI and everything to do with Android native, the only people that can do anything here is the folks at google and I don't think they wanna do anything about it especially since the bug has been open with them since 2018 and they still have not done anything for the last 6 or so years

**Comment by Kaayo** [comment] 2024-05-14 14:07
> I don't think anyone at Microsoft can help us with this, this has nothing to do with .NET or .NET MAUI and everything to do with Android native, the only people that can do anything here are the folks at Google and I don't think they wanna do anything about it especially since the bug has been open with them since 2018 and they still have not done anything for this in the last 6 or so years.

Well, so that we don't end this conversation without a possible solution. I suggest opening an issue in the Android repository and linking our issue there. So at least the new devs who search for your plugin are aware and maybe some of them can help us get Google to take action. Well, I believe it, in case I'm not mistaken. that this bug you reported interferes with technologies other than .NET, such as React Native or Flutter.

**Comment by FreakyAli** [comment] 2024-05-14 14:12
> So face recognition on Android was unsupported until quite recently, it is now supported on Android 10+ and I just got the documentation for it a couple of days ago, for the time being, this is a feature which is in progress, I am planning to add this asap but it might take some time, hope you don't mind.
> 
> More information on this here https://source.android.com/docs/security/features/biometric/face-authentication

I have linked the bug as you can see right at the start of our conversation.

**Comment by FreakyAli** [comment] 2024-05-14 14:25
For future visitors, this cannot be worked on until https://issuetracker.google.com/issues/111315641?pli=1 is fixed by google

**Comment by FreakyAli** [comment] 2024-05-27 06:07
This is pinned and hence I am closing this until future updates to the google issue this is based on, comments are open just in case!

**Closed by FreakyAli** 2024-05-27 06:07 UTC
Labels: wontfix, native-issue
